language: node_js
node_js:
  - "0.10"
  - "0.8"

before_script:
 - npm install -g grunt-cli@0.1.x
 - cd server
 - npm install --quiet
 - node server.js &
 - sleep 3 
 - cd ../client
 - npm install --quiet

services:
  - mongodb

script:
  - grunt
  - cd ../server
  - grunt commit