language: node_js
node_js:
  - "0.10"

before_script:
 - export NODE_TLS_REJECT_UNAUTHORIZED=0
 - npm install -g grunt-cli@0.1.x
 - cd server
 - npm install --quiet
 - node server.js &
 - sleep 3 
 - cd ../client
 - npm install --quiet

services:
  - mongodb
  - redis

script:
  - grunt
  - cd ../server
  - grunt commit