language: node_js
node_js:
  - "0.10.x"
  - "0.8.x"

before_script:
 - npm install -g grunt-cli@0.1.x
 - cd server
 - npm install --quiet
 - node server.js &

services:
  - mongodb

script: grunt commit